export const exampleWorkout = [
  {
    id: "1a3e5965-48b6-46a3-9251-2f565e1746f9",
    name: "Squat (Barbell)",
    bodyParts: "upper legs",
    gifUrl: "",
    sets: ["1", "2", "3"],
    lbs: [205, 195, 185],
    reps: [8, 7, 5],
    createdAt: "2023-09-07T21:03:14.326Z",
    workoutSessionId: "651afd00cf4c35iebfuebgh3",
  },
];

export const bodyParts = [
  "any",
  "back",
  "cardio",
  "chest",
  "lower arms",
  "lower legs",
  "neck",
  "Shoulders",
  "upper arms",
  "upper legs",
  "waist",
];

export const categories = [
  "any",
  "assisted",
  "band",
  "barbell",
  "body weight",
  "bosu ball",
  "cable",
  "dumbbell",
  "elliptical machine",
  "ez barbell",
  "hammer",
  "kettlebell",
  "leverage machine",
  "medicine ball",
  "olympic barbell",
  "resistance band",
  "roller",
  "rope",
  "skierg machine",
  "sled machine",
  "smith machine",
  "stability ball",
  "stationary bike",
  "stepmill machine",
  "tire",
  "trap bar",
  "upper body ergometer",
  "weighted",
  "wheel roller",
];

export const exercises = [
  ["Ab Wheel", "Core"],
  ["Aerobics", "Cardio"],
  ["Arnold Press (Dumbbell)", "Shoulders"],
  ["Around The World", "Chest"],
  ["Bench Press (Barbell)", "Chest"],
  ["Bench Press (Dumbbell)", "Chest"],
  ["Bench Press (Cable)", "Chest"],
  ["Bench Press (Smith Machine)", "Chest"],
  ["Bench Press - Close Grip (Barbell)", "Chest"],
  ["Bench Press - Wide Grip (Barbell)", "Chest"],
  ["Bent Over One Arm Row (Dumbbell)", "Back"],
  ["Bent Over Row (Band)", "Back"],
  ["Bent Over Row (Barbell)", "Back"],
  ["Bent Over Row (Dumbbell)", "Back"],
  ["Bent Over Row - Underhand (Barbell)", "Back"],
  ["Bicep Curl (Barbell)", "Arms"],
  ["Bicep Curl (Cable)", "Arms"],
  ["Bicep Curl (Dumbbell)", "Arms"],
  ["Bicep Curl (Machine)", "Arms"],
  ["Bicycle Crunch", "Core"],
  ["Box Jump", "Legs"],
  ["Box Squat (Barbell)", "Legs"],
  ["Bulgarian Split Squat", "Legs"],
  ["Burpee", "Full Body"],
  ["Back Extension", "Back"],
  ["Back Extension (Machine)", "Back"],
  ["Ball Slams", "Full Body"],
  ["Battle Ropes", "Cardio"],
  ["Bench Dip", "Arms"],
  ["Cable Crossover", "Chest"],
  ["Cable Crunch", "Core"],
  ["Cable Kickback", "Arms"],
  ["Cable Pull Through", "Legs"],
  ["Cable Twist", "Core"],
  ["Calf Press on Leg Press", "Legs"],
  ["Calf Press on Seated Leg Press", "Legs"],
  ["Chest Dip", "Chest"],
  ["Chest Dip (Assisted)", "Chest"],
  ["Chest Fly", "Chest"],
  ["Chest Fly (Band)", "Chest"],
  ["Chest Fly (Dumbbell)", "Chest"],
  ["Chest Press (Band)", "Chest"],
  ["Chest Press (Machine)", "Chest"],
  ["Chin up", "Back"],
  ["Chin up (Assisted)", "Back"],
  ["Clean (Barbell)", "Olympic"],
  ["Clean and Jerk (Barbell)", "Olympic"],
  ["Climbing", "Cardio"],
  ["Concentration Curl (Dumbbell)", "Arms"],
  ["Cross Body Crunch", "Core"],
  ["Crunch", "Core"],
  ["Crunch (Machine)", "Core"],
  ["Crunch (Stability Ball)", "Core"],
  ["Cycling", "Cardio"],
  ["Cycling (indoor)", "Cardio"],
  ["Deadlift (Band)", "Legs"],
  ["Deadlift (Barbell)", "Back"],
  ["Deadlift (Dumbbell)", "Legs"],
  ["Deadlift (Smith Machine)", "Legs"],
  ["Deadlift High Pull (Barbell)", "Olympic"],
  ["Decline Bench Press (Dumbbell)", "Chest"],
  ["Decline Bench Press (Dumbbell)", "Chest"],
  ["Decline Bench Press (Smith Machine)", "Chest"],
  ["Decline Crunch", "Crunch"],
  ["Deficit Deadlift (Barbell)", "Legs"],
  ["Elliptical Machine", "Cardio"],
  ["Face Pull (Cable)", "Shoulders"],
  ["Flat Knee Raise", "Core"],
  ["Flat Leg Raise", "Core"],
  ["Floor Press (Barbell)", "Chest"],
  ["Front Raise (Band)", "Shoulders"],
  ["Front Raise (Barbell)", "Shoulders"],
  ["Front Raise (Cable)", "Shoulders"],
  ["Front Raise (Dumbbell)", "Shoulders"],
  ["Front Raise (Plate)", "Shoulders"],
  ["Front Squat (Barbell)", "Legs"],
  ["Glute Ham Raise", "Legs"],
  ["Glute Kickback (Machine)", "Legs"],
  ["Goblet Squat (Kettlebell)", "Legs"],
  ["Good Morning (Barbell)", "Back"],
  ["Hack Squat (Barbell)", "Legs"],
  ["Hammer Curl (Band)", "Arms"],
  ["Hammer Curl (Cable)", "Arms"],
  ["Hammer Curl (Dumbbell)", "Arms"],
  ["Handstand Push Up", "Legs"],
  ["Hang Clean (Barbell)", "Olympic"],
  ["Hang Snatch (Barbell)", "Olympic"],
  ["Hanging Knee Raise", "Core"],
  ["Hanging Leg Raise", "Core"],
  ["High Knee Skips", "Legs"],
  ["Hiking", "Cardio"],
  ["Hip Abductor (Machine)", "Legs"],
  ["Hip adductor (Machine)", "Legs"],
  ["Hip Thrust (Barbell)", "Legs"],
  ["Hip Thrust (Bodyweight)", "Legs"],
  ["Incline Bench Press (Barbell)", "Chest"],
  ["Incline Bench Press (Cable)", "Chest"],
  ["Incline Bench Press (Dumbbell)", "Chest"],
  ["Incline Bench Press (Smith Machine)", "Chest"],
  ["Incline Chest Fly (Dumbbell)", "Chest"],
  ["Incline Chest Press (Machine)", "Chest"],
  ["Incline Curl (Dumbbell)", "Arms"],
  ["Incline row (Dumbbell)", "Back"],
  ["Inverted Row (Bodyweight)", "Back"],
  ["Iso-Lateral Chest Press (Machine)", "Chest"],
  ["Iso-Lateral Row (Machine)", "Back"],
  ["Jackknife Sit Up", "Core"],
  ["Jump Rope", "Cardio"],
  ["Jump Shrug (Barbell)", "Olympic"],
  ["Jump Squat", "Legs"],
  ["Jumping Jack", "Full Body"],
  ["Kettlebell Swing", "Full Body"],
  ["Kettlebell Turkish Get Up", "Full Body"],
  ["Kipping Pull Up", "Back"],
  ["Knee Raise (Captain's Chair)", "Core"],
  ["Kneeling Pulldown (Band)", "Back"],
  ["Knees to Elbows", "Core"],
  ["Lat Pulldown (Cable)", "Back"],
  ["Lat Pulldown (Machine)", "Back"],
  ["Lat Pulldown (Single Arm)", "Back"],
  ["Lat Pulldown - Underhand (Band)", "Back"],
  ["Lat Pulldown - Underhand (Cable)", "Back"],
  ["Lat Pulldown - Wide Grip (Cable)", "Back"],
  ["Lateral Box Jump", "Legs"],
  ["Lateral Raise (Band)", "Shoulders"],
  ["Lateral Raies (Cable)", "Shoulders"],
  ["Lateral Raise (Dumbbell)", "Shoulders"],
  ["Lateral Raise (Machine)", "Shoulders"],
  ["Leg Extension (Machine)", "Legs"],
  ["Leg Press", "Legs"],
  ["Lunge (Barbell)", "Legs"],
  ["Lunge (Bodyweight)", "Legs"],
  ["Lunge (Dumbbell)", "Legs"],
  ["Lying Leg Curl (Machine)", "Legs"],
  ["Mountain Climber", "Legs"],
  ["Muscle Up", "Full Body"],
  ["Oblique Crunch", "Core"],
  ["Overhead Press (Barbell)", "Shoulders"],
  ["Overhead Press (Cable)", "Shoulders"],
  ["Overhead Press (Dumbbell)", "Shoulders"],
  ["Overhead Press (Smith Machine)", "Shoulders"],
  ["Overhead Squat (Barbell)", "Olympic"],
  ["Pec Deck (Machine)", "Chest"],
  ["Pendlay Row (Barbell)", "Back"],
  ["Pistol Squat", "Legs"],
  ["Plank", "Core"],
  ["Power Clean", "Olympic"],
  ["Power Snatch (Barbell)", "Olympic"],
  ["Preacher Curl (Barbell)", "Arms"],
  ["Preacher Curl (Dumbbell)", "Arms"],
  ["Preacher Curl (Machine)", "Arms"],
  ["Press Under (Barbell)", "Olympic"],
  ["Pull Up", "Back"],
  ["Pull Up (Assisted)", "Back"],
  ["Pull Up (Band)", "Back"],
  ["Pullover (Dumbbell)", "Chest"],
  ["Pullover (Machine)", "Chest"],
  ["Push Press", "Shoulders"],
  ["Push Up", "Chest"],
  ["Push Up (Band)", "Chest"],
  ["Push Up (Knees)", "Chest"],
  ["Rack Pull (Barbell)", "Back"],
  ["Reverse Crunch", "Core"],
  ["Reverse Curl (Band)", "Arms"],
  ["Reverse Curl (Barbell)", "Arms"],
  ["Reverse Curl (Dumbbell)", "Arms"],
  ["Reverse Fly (Cable)", "Shoulders"],
  ["Reverse Fly (Dumbbell)", "Shoulders"],
  ["Reverse Fly (Machine)", "Shoulders"],
  ["Reverse Grip Concentration Curl (Dumbbell)", "Arms"],
  ["Reverse Plank", "Core"],
  ["Romanian Deadlift (Barbell)", "Back"],
  ["Romanian Deadlift (Dumbbell)", "Legs"],
  ["Rowing (Machine)", "Cardio"],
  ["Running", "Cardio"],
  ["Running (Treadmill)", "Cardio"],
  ["Russian Twist", "Core"],
  ["Seated Calf Raise (Machine)", "Legs"],
  ["Seated Calf Raise (Plate Loaded)", "Legs"],
  ["Seated Leg Curl (Machine)", "Legs"],
  ["Seated Leg Press (Machine)", "Legs"],
  ["Seated Overhead Press (Barbell)", "Shoulders"],
  ["Seated Overhead Press (Dumbbell)", "Shoulders"],
  ["Seated Palms Up Wrist Curl (Dumbbell)", "Arms"],
  ["Seated Row (Cable)", "Back"],
  ["Seated Row (Machine)", "Back"],
  ["Seated Wide-Grip Row (Cable)", "Back"],
  ["Shoulder Press (Machine)", "Shoulders"],
  ["Shoulder Press (Plate Loaded)", "Shoulders"],
  ["Shrug (Barbell)", "Shoulders"],
  ["Shrug (Dumbbell)", "Shoulders"],
  ["Shrug (Machine)", "Back"],
  ["Shrug (Smith Machine)", "Back"],
  ["Side Bend (Cable)", "Core"],
  ["Side Bend (Dumbbell)", "Core"],
  ["Side Plank", "Core"],
  ["Single Leg Bridge", "Legs"],
  ["Sit Up", "Core"],
  ["Skating", "Cardio"],
  ["Skiing", "Cardio"],
  ["Skullcrusher (Barbell)", "Arms"],
  ["Skullcrusher (Dumbbell)", "Arms"],
  ["Snatch (Barbell)", "Olympic"],
  ["Snatch Pull (Barbell)", "Olympic"],
  ["Snowboarding", "Cardio"],
  ["Split Jerk (Barbell)", "Olympic"],
  ["Squat (Band)", "Legs"],
  ["Squat (Barbell)", "Legs"],
  ["Squat (Bodyweight)", "Legs"],
  ["Squat (Dumbbell)", "Legs"],
  ["Squat (Machine)", "Legs"],
  ["Squat (Smith Machine)", "Legs"],
  ["Squat Row (Band)", "Full Body"],
  ["Standing Calf Raise (Barbell)", "Legs"],
  ["Standing Calf Raise (Bodyweight)", "Legs"],
  ["Standing Calf Raise (Dumbbell)", "Legs"],
  ["Standing Calf Raise (Machine)", "Legs"],
  ["Standing Calf Raise (Smith Machine)", "Legs"],
  ["Step-up", "Legs"],
  ["Stiff Leg Deadlift (Barbell)", "Back"],
  ["Stiff Leg Deadlift (Dumbbell)", "Legs"],
  ["Straight Leg Deadlift (Band)", "Legs"],
  ["Stretching", "Other"],
  ["Strict Military Press (Barbell)", "Shoulders"],
  ["Sumo Deadlift (Barbell)", "Back"],
  ["Sumo Deadlift High Pull (Barbell)", "Full Body"],
  ["Superman", "Core"],
  ["Swimming", "Cardio"],
  ["T Bar Row", "Back"],
  ["Thruster (Barbell)", "Full Body"],
  ["Thruster (Kettlebell)", "Full Body"],
  ["Toes To Bar", "Core"],
  ["Torso Rotation (Machine)", "Core"],
  ["Trap Bar Deadlift", "Legs"],
  ["Triceps Dip", "Arms"],
  ["Triceps Dip (Assisted)", "Arms"],
  ["Triceps Extension", "Arms"],
  ["Triceps Extension (Barbell)", "Arms"],
  ["Triceps Extension (Cable)", "Arms"],
  ["Triceps Extension (Dumbbell)", "Arms"],
  ["Triceps Extension (Machine)", "Arms"],
  ["Triceps Pushdown (Cable - Straight Bar)", "Arms"],
  ["Upright Row (Barbell)", "Back"],
  ["Upright Row (Cable)", "Arms"],
  ["Upright Row (Dumbbell)", "Shoulders"],
  ["V Up", "Core"],
  ["Walking", "Cardio"],
  ["Wide Pull Up", "Back"],
  ["Wrist Roller", "Arms"],
  ["Yoga", "Cardio"],
  ["Zercher Squat (Barbell)", "Legs"],
];
