export const exercises = [
  ["Ab Wheel", "Core"],
  ["Aerobics", "Cardio"],
  ["Arnold Press (Dumbbell)", "Shoulders"],
  ["Around The World", "Chest"],
  ["Bench Press (Barbell)", "Chest"],
  ["Bench Press (Dumbbell)", "Chest"],
  ["Bench Press (Cable)", "Chest"],
  ["Bench Press (Smith Machine)", "Chest"],
  ["Bench Press - Close Grip (Barbell)", "Chest"],
  ["Bench Press - Wide Grip (Barbell)", "Chest"],
  ["Bent Over One Arm Row (Dumbbell)", "Back"],
  ["Bent Over Row (Band)", "Back"],
  ["Bent Over Row (Barbell)", "Back"],
  ["Bent Over Row (Dumbbell)", "Back"],
  ["Bent Over Row - Underhand (Barbell)", "Back"],
  ["Bicep Curl (Barbell)", "Arms"],
  ["Bicep Curl (Cable)", "Arms"],
  ["Bicep Curl (Dumbbell)", "Arms"],
  ["Bicep Curl (Machine)", "Arms"],
  ["Bicycle Crunch", "Core"],
  ["Box Jump", "Legs"],
  ["Box Squat (Barbell)", "Legs"],
  ["Bulgarian Split Squat", "Legs"],
  ["Burpee", "Full Body"],
  ["Back Extension", "Back"],
  ["Back Extension (Machine)", "Back"],
  ["Ball Slams", "Full Body"],
  ["Battle Ropes", "Cardio"],
  ["Bench Dip", "Arms"],
  ["Cable Crossover", "Chest"],
  ["Cable Crunch", "Core"],
  ["Cable Kickback", "Arms"],
  ["Cable Pull Through", "Legs"],
  ["Cable Twist", "Core"],
  ["Calf Press on Leg Press", "Legs"],
  ["Calf Press on Seated Leg Press", "Legs"],
  ["Chest Dip", "Chest"],
  ["Chest Dip (Assisted)", "Chest"],
  ["Chest Fly", "Chest"],
  ["Chest Fly (Band)", "Chest"],
  ["Chest Fly (Dumbbell)", "Chest"],
  ["Chest Press (Band)", "Chest"],
  ["Chest Press (Machine)", "Chest"],
  ["Chin up", "Back"],
  ["Chin up (Assisted)", "Back"],
  ["Clean (Barbell)", "Olympic"],
  ["Clean and Jerk (Barbell)", "Olympic"],
  ["Climbing", "Cardio"],
  ["Concentration Curl (Dumbbell)", "Arms"],
  ["Cross Body Crunch", "Core"],
  ["Crunch", "Core"],
  ["Crunch (Machine)", "Core"],
  ["Crunch (Stability Ball)", "Core"],
  ["Cycling", "Cardio"],
  ["Cycling (indoor)", "Cardio"],
  ["Deadlift (Band)", "Legs"],
  ["Deadlift (Barbell)", "Back"],
  ["Deadlift (Dumbbell)", "Legs"],
  ["Deadlift (Smith Machine)", "Legs"],
  ["Deadlift High Pull (Barbell)", "Olympic"],
  ["Decline Bench Press (Dumbbell)", "Chest"],
  ["Decline Bench Press (Dumbbell)", "Chest"],
  ["Decline Bench Press (Smith Machine)", "Chest"],
  ["Decline Crunch", "Crunch"],
  ["Deficit Deadlift (Barbell)", "Legs"],
  ["Elliptical Machine", "Cardio"],
  ["Face Pull (Cable)", "Shoulders"],
  ["Flat Knee Raise", "Core"],
  ["Flat Leg Raise", "Core"],
  ["Floor Press (Barbell)", "Chest"],
  ["Front Raise (Band)", "Shoulders"],
  ["Front Raise (Barbell)", "Shoulders"],
  ["Front Raise (Cable)", "Shoulders"],
  ["Front Raise (Dumbbell)", "Shoulders"],
  ["Front Raise (Plate)", "Shoulders"],
  ["Front Squat (Barbell)", "Legs"],
  ["Glute Ham Raise", "Legs"],
  ["Glute Kickback (Machine)", "Legs"],
  ["Goblet Squat (Kettlebell)", "Legs"],
  ["Good Morning (Barbell)", "Back"],
  ["Hack Squat (Barbell)", "Legs"],
  ["Hammer Curl (Band)", "Arms"],
  ["Hammer Curl (Cable)", "Arms"],
  ["Hammer Curl (Dumbbell)", "Arms"],
  ["Handstand Push Up", "Legs"],
  ["Hang Clean (Barbell)", "Olympic"],
  ["Hang Snatch (Barbell)", "Olympic"],
  ["Hanging Knee Raise", "Core"],
  ["Hanging Leg Raise", "Core"],
  ["High Knee Skips", "Legs"],
  ["Hiking", "Cardio"],
  ["Hip Abductor (Machine)", "Legs"],
  ["Hip adductor (Machine)", "Legs"],
  ["Hip Thrust (Barbell)", "Legs"],
  ["Hip Thrust (Bodyweight)", "Legs"],
  ["Incline Bench Press (Barbell)", "Chest"],
  ["Incline Bench Press (Cable)", "Chest"],
  ["Incline Bench Press (Dumbbell)", "Chest"],
  ["Incline Bench Press (Smith Machine)", "Chest"],
  ["Incline Chest Fly (Dumbbell)", "Chest"],
  ["Incline Chest Press (Machine)", "Chest"],
  ["Incline Curl (Dumbbell)", "Arms"],
  ["Incline row (Dumbbell)", "Back"],
  ["Inverted Row (Bodyweight)", "Back"],
  ["Iso-Lateral Chest Press (Machine)", "Chest"],
  ["Iso-Lateral Row (Machine)", "Back"],
  ["Jackknife Sit Up", "Core"],
  ["Jump Rope", "Cardio"],
  ["Jump Shrug (Barbell)", "Olympic"],
  ["Jump Squat", "Legs"],
  ["Jumping Jack", "Full Body"],
  ["Kettlebell Swing", "Full Body"],
  ["Kettlebell Turkish Get Up", "Full Body"],
  ["Kipping Pull Up", "Back"],
  ["Knee Raise (Captain's Chair)", "Core"],
  ["Kneeling Pulldown (Band)", "Back"],
  ["Knees to Elbows", "Core"],
  ["Lat Pulldown (Cable)", "Back"],
  ["Lat Pulldown (Machine)", "Back"],
  ["Lat Pulldown (Single Arm)", "Back"],
  ["Lat Pulldown - Underhand (Band)", "Back"],
  ["Lat Pulldown - Underhand (Cable)", "Back"],
  ["Lat Pulldown - Wide Grip (Cable)", "Back"],
  ["Lateral Box Jump", "Legs"],
  ["Lateral Raise (Band)", "Shoulders"],
  ["Lateral Raies (Cable)", "Shoulders"],
  ["Lateral Raise (Dumbbell)", "Shoulders"],
  ["Lateral Raise (Machine)", "Shoulders"],
  ["Leg Extension (Machine)", "Legs"],
  ["Leg Press", "Legs"],
  ["Lunge (Barbell)", "Legs"],
  ["Lunge (Bodyweight)", "Legs"],
  ["Lunge (Dumbbell)", "Legs"],
  ["Lying Leg Curl (Machine)", "Legs"],
];
